# Specify a non-default branch for pull requests by dependabot

version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "weekly"
          # Check for npm updates on Wednesdays
          day: "wednesday"
      target-branch: "develop"
      # Disable version updates (this option should have no impact on security updates)
      open-pull-requests-limit: 0      
      # Labels on pull requests for security and version updates
      labels:
          - "dependencies"
