language: node_js
node_js: 10
matrix:
  include:
  - os: linux
    dist: trusty
  - os: osx
    osx_image: xcode8.3
env:
  global:
  - GITHUB_REPO: bitshares/beet
  - secure: CCFEuKsekI/PvoVeSvrBYHgAz/daHJukqktOoviPn1tJnIFCJzNeyhNyepSQSb48QJLeWepkjDTGEbyBBMqbCE+D+M4bDNdSynlBhX/fN8vK2uKYw9MFjdhTo50/ZR1oNY0rhEVmU4zznxsNecYSFAOkq8/XHviBspko14aTcfataZO5vOpJvKoM1pA8nk45C7zjXaK1W3T4Zhx1rQO83yI28mjhbKEWnnSj/g5CrkVBZmuyzhq2ocB2lk1HX5HJFtqLHIRUpX+ERQHSK2VhnAllb5OrIpnZYuMOe3pLWMbnOXcUiy+/+DCWInk/i+JLoGktx2kIpUZ6y4uoxOgdVLZns7A1AcuROYa/5jLbJGhxFPl15jzJS64REOkyuCvjG1zjnITy2Z2UZGh2nIgCJSHPyfy/LbUiBdYqWsFewUiVBvp9nm9kTkoMQihiMOwBsBN9L5JuQ7W87epPNCMSKdymvTzjlS2yshRdAho+j23g6bGahgEwweGUdBHzG3B7aICkjP/nnblnV/k2Ku3lDQmViBYQSAqL1ujGRoxhLC+qckGnjop3yYZjbG92T43Qptp/k5n58GhO510xl2C9iTEP8iLU0hWTAU45dGaVjB/vx2ACB2psJ584bwRsqQM8ZF3DfbTnR1M/Sp8iblFjV9ICuPfv2kMVFohuo44CRzQ=
cache:
  directories:
  - node_modules
  - $HOME/.cache/electron
  addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - icnsutils
    - graphicsmagick
    - xz-utils
    - fakeroot
install:
  - npm ci
  - npm install electron-builder
  - npm install electron-installer-debian
script: "./package.sh"
after_success: "./publish.sh"