language: node_js
node_js: 12
matrix:
  include:
  - os: osx
    osx_image: xcode10.2
  - os: linux
    sudo: required
    dist: xenial
    before_install:
    - sudo apt-get install --no-install-recommends -y libopenjp2-tools
    - sudo apt-get install --no-install-recommends -y rpm
    addons:
      snaps:
      - name: snapcraft
        classic: true
env:
  global:
  - GITHUB_REPO: bitshares/beet
  - secure: abv21fB7gKbkYLHChvNptwi3wc1szvxLx+lBGEBsfpv06vJbbJ0fqs317pVQghkpmsdCV440SJ6eC4qD1h2CtN3++VNlkFQcvI9we46VdHIiO15JB/SB/X/fGSIyu5pRWE5xLs30HXk3zYY8xezb1p8rzA/vLbAz+Kfr30iVnaIXBIokAyUjd60V7eIU0uDl+czK42aJEgq4hSfpIAXDinBizAjqnYIJTWSLIYMM6+LQA8nuRWxfq3BANmn/MZOelmLtLOyipnhrENubOkvISpj++MU+0eHYlHryMsP93vEYUqJq0rw1El99eB8IokVEJpvpjmPpopxPo4X+H5kQhewwWkXPiOM6VeV35DSb84AnCmsA+HfaZDLMkz4wbUVJsRuFjmc4PIHPFaGISMsU5Oonsal4hnMDTN5pwhhc7hkGEBza1HXQaNunmdYxuEGvPIls5Adx6jZQD5VE4OcpHHauhDYuta16raNtcO42yN+JR+UrC0gzqMYwNRzpErtFNnrW+69R/84CtDWIcan2eQ0WbxsvpO9Ixyuvp9DEwj5tQosCP16gfnlzJxmUfgvJalG6tFbGXepE3MB1utUt3CTx4R71iuX5Xk4fdH9BZZjyb7z53Jh3XLm3yLKklnPP58YFT7WyHDOXmjcQ4g7uTdWlH1t5Kv5kKbzVjTI7Hq4=

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc
    - g++
    - icnsutils
    - build-essential
    - libopenjp2-tools
    - libstdc++6
    - graphicsmagick
    - xz-utils
    - fakeroot
    - rpm
    - libusb-dev
    - libudev-dev
    - rpm
install:
- npm ci
script:
- PACKAGE_VERSION=$(node -p -e "require('./package.json').version")
- npm run build
- bash publish.sh
deploy:
- provider: releases
  file_glob: true
  api_key:
    secure: abv21fB7gKbkYLHChvNptwi3wc1szvxLx+lBGEBsfpv06vJbbJ0fqs317pVQghkpmsdCV440SJ6eC4qD1h2CtN3++VNlkFQcvI9we46VdHIiO15JB/SB/X/fGSIyu5pRWE5xLs30HXk3zYY8xezb1p8rzA/vLbAz+Kfr30iVnaIXBIokAyUjd60V7eIU0uDl+czK42aJEgq4hSfpIAXDinBizAjqnYIJTWSLIYMM6+LQA8nuRWxfq3BANmn/MZOelmLtLOyipnhrENubOkvISpj++MU+0eHYlHryMsP93vEYUqJq0rw1El99eB8IokVEJpvpjmPpopxPo4X+H5kQhewwWkXPiOM6VeV35DSb84AnCmsA+HfaZDLMkz4wbUVJsRuFjmc4PIHPFaGISMsU5Oonsal4hnMDTN5pwhhc7hkGEBza1HXQaNunmdYxuEGvPIls5Adx6jZQD5VE4OcpHHauhDYuta16raNtcO42yN+JR+UrC0gzqMYwNRzpErtFNnrW+69R/84CtDWIcan2eQ0WbxsvpO9Ixyuvp9DEwj5tQosCP16gfnlzJxmUfgvJalG6tFbGXepE3MB1utUt3CTx4R71iuX5Xk4fdH9BZZjyb7z53Jh3XLm3yLKklnPP58YFT7WyHDOXmjcQ4g7uTdWlH1t5Kv5kKbzVjTI7Hq4=
  file: 
    - "dist/BeetSetup.deb"
    - "dist/BeetSetup.rpm"
    - "dist/BeetSetup.dmg"
    - "dist/BeetSetup.dmg.blockmap"
    - "dist/BeetSetup.zip"
    - "dist/BeetSetup.AppImage"
    - "dist/*.yml"
  skip_cleanup: true
  prerelease: true
  name: ${RELEASE_NAME}
  body: ${RELEASE_DESC}
  on:
    repo: bitshares/beet
    tags: true