version: 0.1.{build}
environment:
    nodejs_version: 10
install:
    # Get the latest stable version of Node.js or io.js
    - ps: Install-Product node $env:nodejs_version
    # install modules
    - npm ci
build: off
platform:
    - x64
before_package: echo Before package
test_script:
    - npm run make