version: Beet-{build}
image: Visual Studio 2017
max_jobs: 3
platform:
  - x64
environment:
  nodejs_version: 12
  GITHUB_TOKEN:
      secure: 6ld2MBbd9Dep8sD6q3on5JHh2QBG2dSOPwS4Gp4/mG7/RLXdrB9H/ibNXI+4FeX+
branches:
  only:
    - master
    - develop
    - scaffold-refactor
cache:
  - node_modules
  - '%USERPROFILE%\.electron'
init:
  - git config --global core.autocrlf input
install:
  - ps: Install-Product node 12 x64
  - ps: $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version
  - ps: Update-AppveyorBuild -Version "$env:package_version-$env:APPVEYOR_BUILD_NUMBER"
  - yarn
build_script:
  - yarn dist
build: on
artifacts:
- path: dist/*.exe
  name: BeetSetup
- path: dist/*.exe.blockmap
  name: BeetSetupBlockMap
deploy:
- provider: GitHub
  release: Beet Installer v$(package_version)
  description: "This is the latest Beet Installer"
  auth_token:
    secure: 6ld2MBbd9Dep8sD6q3on5JHh2QBG2dSOPwS4Gp4/mG7/RLXdrB9H/ibNXI+4FeX+
  repository: bitshares/beet
  prerelease: true
  force_update: true
  on:
    APPVEYOR_REPO_TAG: true
- provider: GitHub  
  release: Beet Installer DEV v$(package_version)-$(APPVEYOR_REPO_COMMIT)
  description: "This is a snapshot installer of the latest develop branch. May contain bugs. Not suited for normal use."
  auth_token:
    secure: 6ld2MBbd9Dep8sD6q3on5JHh2QBG2dSOPwS4Gp4/mG7/RLXdrB9H/ibNXI+4FeX+
  repository: bitshares/beet
  prerelease: true
  on:
    branch: develop
#- provider: GitHub  
#  release: Refactor Beet Installer v$(package_version)-$(APPVEYOR_REPO_COMMIT)
#  description: "This is a one-off installer of a specific branch. May contain bugs. Not suited for normal use. Will be removed"
#  auth_token:
#    secure: jr08/oNuLLnJAth0P0/KslT6bJPfGGA/QkkPWo83z82i0R+U6jJMZxWVrqDBMXKL
#  repository: bitshares/beet
#  draft: true
#  on:
#    branch: scaffold-refactor